---
title: "CCLE_ExtendedData_Fig1"
output: html_document
date: "2025-02-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(GSVA)
library(clusterProfiler)
library(GseaVis)

library(readxl)
library(dplyr)
library(ggplot2)
library(ggpubr)

library(patchwork)
```


```{r load_data}
sample3 <- read.csv('Model.csv')
#Select Males
sample3 <- sample3[sample3$Sex=='Male',]

IDmap <- read.csv('OmicsDefaultModelProfiles.csv')
rownames(IDmap)<-IDmap$ProfileID

CNSegment <- read.csv('OmicsCNSegmentsProfile.csv')
CNSegment$ModelID <- IDmap[CNSegment$ProfileID,'ModelID']
CNSegment <- CNSegment[CNSegment$ModelID %in% sample3$ModelID,]
```

```{r Calculate YchrS}
Expr <- read.csv('OmicsExpressionProteinCodingGenesTPMLogp1BatchCorrected.csv')
gene_name <- c()
for(gene in colnames(Expr)){
  gene <- strsplit(gene, split='\\.')
  gene_name <- c(gene_name, gene[[1]][[1]])
}

colnames(Expr) <- gene_name
rownames(Expr) <-Expr[,1]
Expr <- Expr[,-1]
YchrS = list('Ychr'=c('DDX3Y', 'UTY', 'KDM5D', 'USP9Y', 'ZFY', 'RPS4Y1', 'TMSB4Y', 'EIF1AY', 'NLGN4Y'))

gsvaPar <- gsvaParam(as.matrix(t(Expr)), YchrS)
tcga_gsva2 <- gsva(gsvaPar)
tcga_gsva2 <- as.data.frame(t(tcga_gsva2))
write.csv(tcga_gsva2,'CCLE_YchrS_TPM_bacorr.csv')

```

```{r}
tcga_gsva2 <- read.csv('CCLE_YchrS_TPM_bacorr.csv')
rownames(tcga_gsva2) <- tcga_gsva2$X
tcga_gsva2$ModelID <- tcga_gsva2$X
#Select male
tcga_gsva2<-tcga_gsva2[tcga_gsva2$ModelID %in% sample3$ModelID,]
#Define YchrS level
rownames(tcga_gsva2) <- tcga_gsva2$ModelID
tcga_gsva2$LOY_BR <- ifelse(tcga_gsva2$Ychr>=mean(tcga_gsva2$Ychr),'WTY_BR','LOY_BR')
#Combine with CNSegment
CNSegment$YchrS <- tcga_gsva2[CNSegment$ModelID,'Ychr']
CNSegment$LOY_BR <- tcga_gsva2[CNSegment$ModelID,'LOY_BR']

```

```{r ExtendedData Fig1c}
CNSegment <- CNSegment[!is.na(CNSegment$YchrS),]
for(i in chr){
  sub_CNSegment <- CNSegment[CNSegment$Chromosome==i,]
  sub_CNSegment$mid <- (sub_CNSegment$Start + sub_CNSegment$End)/2
  sub_CNSegment$logMean <- log2(sub_CNSegment$SegmentMean)
  p<-ggplot(sub_CNSegment,aes(x=mid,y=logMean, color=LOY_BR)) + geom_point(size=0.8) + guides(color='none') + 
    scale_color_manual(values=c('WTY_BR'='#AEC7E8','LOY_BR'='#FF9896'))+
    theme_classic()+
    labs(title = paste0('Chr',i))+
    theme(axis.text.x = element_text(size=5),axis.text.y = element_text(size=5))
  if(i=='1') P = p else P = P+p
  
  pdf(paste0('CCLE_male_Chr',i,'_scatter.pdf'),2,2)
  print(p)
  dev.off()
} 
```

```{r Calculate weigted score}
sample3 <- sample3[sample3$ModelID %in% CNSegment$ModelID, ]
rownames(sample3) <- sample3$ModelID
Score_Cal <- function(CNSegment){
  return(sum(CNSegment$len*CNSegment$SegmentMean)/sum(CNSegment$len))
}
Chr_scores <- data.frame()
for(id in sample3$ModelID){
  sub_CNSegment <- CNSegment[CNSegment$ModelID==id,]
  sub_CNSegment$len <- sub_CNSegment$End-sub_CNSegment$Start
  
  sub_CNSegment[sub_CNSegment$Chromosome=='Y' & sub_CNSegment$End<=2781479,'chromosome'] <-'ParY' #PAR#1 10001-2781479
  sub_CNSegment[sub_CNSegment$Chromosome=='Y' & sub_CNSegment$Start>=56887903,'chromosome'] <-'ParY' #PAR#2 56887903 - 57217415
  
  chr_s<-data.frame(tapply(sub_CNSegment,sub_CNSegment$Chromosome,Score_Cal))
  colnames(chr_s) <- c(id)
  chr_s<-data.frame(t(chr_s))
  Chr_scores <- bind_rows(Chr_scores,chr_s)
}
```

```{r}
Chr_scores$LOY_BR <- tcga_gsva2[rownames(Chr_scores),'LOY_BR']
Chr_scores$YchrS <- tcga_gsva2[rownames(Chr_scores),'Ychr']
```

```{r ExtendedData Fig1d}
Chr_scores <- Chr_scores[!is.na(Chr_scores$Y),]

modelID<-rep(rownames(Chr_scores),length(chr))
scores<-c()
Chr<-rep(chr,each=nrow(Chr_scores))
LOY_BR<-rep(Chr_scores$LOY_BR,length(chr))

chrom <- c(paste0('X',chr[1:22]),'X','Y')
for(i in chrom){
  scores <- c(scores,Chr_scores[[i]])
}
data<-data.frame(modelID,scores,Chr,LOY_BR)
data<-na.omit(data)

data$Chr <- factor(data$Chr,levels = chr)
data$LOY_BR <- factor(data$LOY_BR,levels = c('WTY_BR', 'LOY_BR'))
p <- ggplot(data, aes(x=Chr,y=scores,fill=LOY_BR))+
  geom_bar(stat='summary',fun='mean',position=position_dodge(),width=0.8,color='black')+
  stat_summary(fun.data = 'mean_se',geom = 'errorbar',colour='black',width=0.15,position=position_dodge(.8))+
  scale_fill_manual(values=c('WTY_BR'='#AEC7E8','LOY_BR'='#FF9896'))+#guides(fill=FALSE)+
  stat_compare_means(method="wilcox.test",paired=F,aes(group=LOY_BR,label = 'p.value'), label.y=1.27, tip.length=0.01,vjust=0.2,size=2)+
  scale_y_continuous(expand = expansion(mult = 0))+coord_cartesian(ylim=c(0,1.3))+
  theme_classic()
pdf(paste0('CCLE_male_Chr_weighted_score_bar.pdf'),6,3)
print(p)
dev.off()
```

```{r ExtendedData Fig1d}
for(i in chrom){
  sub_Chr_scores <- Chr_scores[,c(i,'LOY_BR','YchrS')]
  colnames(sub_Chr_scores) <- c('Chr_scores','LOY_BR','YchrS')
  p<-ggplot(sub_Chr_scores,aes(x=Chr_scores,y=YchrS, color=LOY_BR)) + geom_point(size=0.5) +
    scale_color_manual(values=c('WTY_BR'='#AEC7E8','LOY_BR'='#FF9896'))+
    theme_classic()+
    labs(title = paste0(i))+
    theme(axis.text.x = element_text(size=5),axis.text.y = element_text(size=5))
  if(i=='X1') P = p else P = P+p
  pdf(paste0('CCLE_male_Chr_YchrSvs',i,'_scatter.pdf'),2.8,1.5)
  print(p)
  dev.off()
}
```

