---
title: "TCGA_Clin_characteristics_Figure1"
output: html_document
date: "2024-06-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pakages}
library(ComplexHeatmap)
library(readxl)
library(RColorBrewer)
library(clusterProfiler)
library(circlize)
library(maftools)
library(rtracklayer)
library(pROC)
library(ggplot2)
library(ggpubr)
library(survival)
library(survminer)
library(scales)
```

```{r Fig1a}
expr_LOY <- read.table('expr_LOY_allgenes_FPKM.txt')
#Select Ychr genes
row_ann<- data.table::fread("New_Ychr genelist.txt")
row_ann<-row_ann[row_ann$SYMBOL %in% rownames(expr_LOY),]
Exprdata<-expr_LOY[row_ann$SYMBOL,]
#Select and sort 4127 samples
top_ann <- read_excel("Extended Data Table 1.xlsx")
colnames(Exprdata) <- substr(colnames(Exprdata),1,nchar(colnames(Exprdata))-3)
top_ann$Sample <- gsub('-','.',top_ann$Sample)
top_ann$Y_status <- factor(top_ann$Y_status,levels=c("LOY","WT"))
sOrder <- order(top_ann$Y_status,top_ann$CancerType)
top_ann <- top_ann[sOrder,]
Exprdata<-Exprdata[,top_ann$Sample]
#Scale Expression matrix
ml  <-  t(scale(t(Exprdata),center = TRUE,scale = TRUE))
ml[ml > 1.5] <- 1.5
ml[ml < -1.5] <- -1.5
#Top annotations
col = list(Y_status = c("LOY" ="#a81726", "WT"="#1e5ba2"),
            CancerType = c(
                        PRAD = "#682471",PCPG = "#7954BB",THYM = "#BEBADA",THCA = "#C2A5CF",BRCA = "#60636A",
                        TGCT = "#3288BD",SARC = "#7390E3", LIHC = "#96C5E2",LGG = "#006837",LAML = "#6CC08B",
                        MESO = "#B3DE69",DLBC = "#C7EAE5",CHOL = "#35978F",GBM = "#3A7C89",ACC = "#01665E",
                        SKCM = "#BF812D",BLCA = "#DFC27D",PAAD = "#FEF6B5",LUAD = "#FEE08B",UVM = "#FDB863",
                        KIRC = "#F7945D",COAD = "#F46D43",HNSC = "#F1B6DA",READ = "#D01C8B",KICH = "#E38191",
                        LUSC = "#CC607D",STAD = "#B2182B",KIRP = "#A5ACAF",
                        ESCA = "#2166AC"), 
            YchrS = colorRamp2(c(min(top_ann$YchrS),max(top_ann$YchrS)),c('#FEF6B5','#FDAE61')),
            Age = colorRamp2(c(min(na.omit(top_ann$Age)),max(na.omit(top_ann$Age))),c('#FCCDE5','#CC607D'))
           )
ha <- HeatmapAnnotation(
  Y_status = as.factor(top_ann$Y_status),
  CancerType = as.factor(top_ann$CancerType),
  YchrS = as.matrix(top_ann$YchrS),
  Age = as.matrix(top_ann$Age),
  show_annotation_name = FALSE,
  na_col = "white",
  col = col,
  show_legend = rep(TRUE, 4), 
  annotation_height = unit.c(unit.c(rep(unit(0.3, "cm"), 7)))

)
#Plotting
ml2 <- na.omit(ml)
col_fun <- colorRampPalette(c("#009ac6","#f2f2f1","#f15e4c"))(10000)
genes = c('DDX3Y', 'UTY', 'KDM5D', 'USP9Y', 'ZFY', 'RPS4Y1', 'TMSB4Y', 'EIF1AY', 'NLGN4Y')
ht <- Heatmap((ml2),top_annotation = ha,
              col=col_fun,
              column_split=top_ann$Y_status,
              column_gap = unit(1, "mm"),border = F,
              cluster_rows = TRUE, show_column_names = FALSE, 
              cluster_columns = FALSE,use_raster = TRUE
) + rowAnnotation(link = anno_mark(at = which(rownames(ml2) %in% genes), 
                                  labels = genes, labels_gp = gpar(fontsize = 15)))

pdf("Figure1a_Ychr_gene_expr.pdf", 10, 7)
draw(ht) 
dev.off()
```

```{r Fig 1c}
data <- read_excel('Extended Data Table 1.xlsx')
data$Y_status <- factor(data$Y_status,levels=c('WT','LOY'))
#ROC calculation
roc_obj_YchrS<- roc(data,Y_status,YchrS)
roc_obj_YwholeS<- roc(data,Y_status,YwholeS)
auc_YchrS <- roc_obj_YchrS$auc
auc_YwholeS <- roc_obj_YwholeS$auc
cmp <- roc.test(roc_obj_YchrS, roc_obj_YwholeS)
#Plotting
p<-ggroc(list(YchrS=roc_obj_YchrS, YwholeS=roc_obj_YwholeS), 
         size=1)+ 
  scale_colour_manual(values = c('#f39e7c','#607bb8'))+
  geom_segment(aes(x = 0, y = 1, xend = 1, yend = 0), 
               colour='grey')+
  annotate('text',x=0.3,y=0.3,label= 'YchrS vs. YwholeS')+
  annotate('text',x=0.3,y=0.2,label= sprintf("P = %.4f",cmp$p.value))+
  annotate('text',x=0.2,y=0.08,label= sprintf("AUC = %.4f",auc_YchrS))+
  annotate('text',x=0.2,y=0.02,label= sprintf("AUC = %.4f",auc_YwholeS))+
  theme_classic()+
  guides(color=guide_legend(override.aes=list(fill=NA)))+
  theme(
        panel.border = element_rect(fill=NA,color="black", linewidth=1, linetype="solid"),
        legend.title = element_blank(), legend.position = c(0.5,0.1)
  )
pdf("Fig1c_YchrSvsYwholeS_box.pdf", width = 5, height = 5)
print(p)
dev.off()
```

```{r ExtendedData_Fig2c}
Coords <- coords(roc_obj_YchrS, 'all', transpose = FALSE)
dots <- data.frame('cutoffs'=c(mean(data$YchrS),median(data$YchrS)), 'label'=c('mean','median'))
Coords <- coords(roc_obj_YchrS, x = dots$cutoffs, input = "threshold")
Coords$label <- dots$label
```


```{r ExtendedData_Fig2c}
library(tibble)
p<-ggroc(list(YchrS=roc_obj_YchrS, YwholeS=roc_obj_YwholeS), size=1)+ 
  scale_colour_manual(values = c('#f39e7c','#607bb8'))+
  geom_segment(aes(x = 0, y = 1, xend = 1, yend = 0), colour='grey')+
  annotate('text',x=0.3,y=0.3,label= 'YchrS vs. YwholeS')+
  annotate('text',x=0.3,y=0.2,label= sprintf("P = %.4f",cmp$p.value))+
  annotate('text',x=0.2,y=0.08,label= sprintf("AUC = %.4f",auc_YchrS))+
  annotate('text',x=0.2,y=0.02,label= sprintf("AUC = %.4f",auc_YwholeS))+
  theme_classic()+
  guides(color=guide_legend(override.aes=list(fill=NA)))+
  theme(
        panel.border = element_rect(fill=NA,color="black", linewidth=1, linetype="solid"),
        legend.title = element_blank(), legend.position = c(0.5,0.1)
  )

Coords$name <- "YchrS"
p <- p+geom_point(data = Coords, mapping = aes(x=specificity, y=sensitivity,colour=label))+
   scale_color_manual(values=c('YchrS'='#f39e7c','YwholeS'='#607bb8', "mean"="red","median"= "#7390E3"))
  
pdf("ExtendedData_Fig2c_YchrSvsYwholeS_box_2.pdf", width = 5, height = 5)
print(p)
dev.off()
```

```{r ExtendedData_Fig2d}
mu <- mean(data$YchrS)
mid <- median(data$YchrS)

pdf('ExtendedData_Fig2d_TCGA_YchrS_distribution_surv.pdf',4,3)
p<-ggplot(data,aes(x=YchrS))+geom_density()+
  geom_vline(aes(xintercept=mu),color="red",linetype="dashed")+
  geom_text(aes(x=mu ,y=4, label="mean"),color="red")+
  geom_vline(aes(xintercept=mid),color="blue",linetype="dashed")+
  geom_text(aes(x=mid ,y=5, label="median"),color="blue")+
  theme_classic()+xlab("YchrS")+ylab('Density')
print(p)
dev.off()
```

```{r Fig 1d}
data<-read_excel('Extended Data Table 1.xlsx')
data <- data[,c('YchrS','Age_seg')]
data <- na.omit(data)
data$Age_seg <- ordered(data$Age_seg,levels=c('20-39','40-59','60-79','>79'))
my_com <- list(c('60-79','>79'),c('40-59','60-79'),c('20-39','40-59'))
p <- ggplot(data,aes(x=Age_seg,y=YchrS,fill=Age_seg))+
  geom_bar(stat='summary',fun='mean',position=position_dodge(),width=0.8,color='black')+
  stat_summary(fun.data = 'mean_se',geom = 'errorbar',colour='black',width=0.15,position=position_dodge(.8))+
  scale_fill_manual(values=c('#FDB863','#96C5E2','#C2A5CF','#6CC08B'))+guides(fill=FALSE)+
  stat_compare_means(comparisons=my_com,method="wilcox.test",paired=F,aes(label=..p.value), label.y=seq(0.35,0.55,by=0.02), tip.length=0.01,vjust=0.2,size=2)+  
  scale_y_continuous(expand = expansion(mult = 0))+coord_cartesian(ylim=c(0,0.45))+
  theme_classic()
pdf('Fig1e_TCGA_barplot_age_R.pdf',2,2)
print(p)
dev.off()
```

```{r Fig 1e}
data<-read_excel('Extended Data Table 1.xlsx')
data <- data[,c('YchrS','Race')]
data$Race <- factor(data$Race,levels=c('WHITE','ASIAN','BLACK OR AFRICAN AMERICAN'))
#Not including AMERICAN INDIAN OR ALASKA NATIVE for small sample size
data <- na.omit(data)
my_com <- list(c('ASIAN','BLACK OR AFRICAN AMERICAN'),c('WHITE','ASIAN'), 
             c('WHITE','BLACK OR AFRICAN AMERICAN'))
p <- ggplot(data,aes(x=Race,y=YchrS,fill=Race))+
  geom_boxplot(position=position_dodge(),width=0.8,color='#60636A',outlier.size = 0.03)+guides(fill=F)+
  geom_jitter(width = 0.3, size=0.01,aes(colour=Race))+guides(colour=F)+
  scale_fill_manual(values=c('#96C5E2','#FDB863','#C2A5CF'))+
  scale_color_manual(values=c("#3288BD","#F7945D","#682471"))+
  stat_compare_means(comparisons=my_com,method="wilcox.test",paired=F,aes(label=..p.value), 
                     label.y=seq(0.52,0.72,by=0.05), tip.length=0.01,vjust=0.2,size=2)+  
  scale_y_continuous(expand = expansion(mult = 0))+coord_cartesian(ylim=c(-0.1,0.75))+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 10,hjust=1))
pdf('Fig1e_TCGA_boxplot_race_R.pdf',2,2.5)
print(p)
dev.off()
```

```{r Fig 1f}
data<-read_excel('Extended Data Table 1.xlsx')
data <- data[data$CancerType=='HNSC',]
data$HBV<-factor(data$HBV, levels = c('Negative','Positive'))
data <- data[,c('YchrS','HPV')]
data <- na.omit(data)
my_com<-list(c('Negative','Positive')) 
p <- ggplot(data,aes(x=HPV,y=YchrS,fill=HPV))+
  geom_boxplot(position=position_dodge(),width=0.8,color='#60636A',notch=TRUE,outlier.size = 0.5)+
  guides(fill=FALSE)+
  geom_jitter(width = 0.3, size=0.1,alpha=0.5,col='#01665E')+
  scale_fill_manual(values=c('#C7EAE5','#35978F'))+
  stat_compare_means(comparisons=my_com,method="wilcox.test",paired=F,aes(label=..p.value),
                     label.y=0.55, tip.length=0.01,vjust=0,size=2)+
  scale_y_continuous(expand = expansion(mult = 0))+coord_cartesian(ylim=c(-0.2,0.62))+
  theme_classic()
pdf('Fig1f_TCGA_boxplot_HPV_R_.pdf',2,2)
print(p)
dev.off()
```

```{r Fig1h}
data <- read_excel('Extended Data Table 1.xlsx')
surv <- read.csv('ExtendedData_Table2_Survival.csv')
data <- merge.data.frame(data, surv, by='Sample')
data$YchrS_level <- factor(data$YchrS_level,c('LOY_BR','WTY_BR'))
surv_type <- c('OS','DSS')
for(s in surv_type){
  rt <- data[, c(paste0(s,'.time'),s,'YchrS_level') ]
  colnames(rt) <- c("Surv_TIME", "Surv_STATUS","risk")
  rt <- na.omit(rt)
  rt$Surv_TIME <- rt$Surv_TIME/365 #Transform to year
  rt$risk <- factor(rt$risk, levels=c('WTY_BR','LOY_BR'))
    
  fit <- survfit(Surv(Surv_TIME, Surv_STATUS) ~ risk, data = rt)
  res.cox <- coxph(Surv(Surv_TIME, Surv_STATUS) ~ risk, data = rt)
  res.cox <- summary(res.cox)
  p.val <- res.cox$coefficients[5]
  HR <- res.cox$conf.int[1]
  up95 <- res.cox$conf.int[4]
  low95 <- res.cox$conf.int[3]
  
  HR <- paste("Hazard Ratio = ", round(HR, 2), sep = "")
  CI <- paste("95% CI: ", paste(round(low95, 2), round(up95, 2), sep = " - "), sep = "")
  p <- ggsurvplot(fit, data = rt, 
                  pval = paste(s,ifelse(p.val < 0.0001, "P < 0.0001", paste("P = ", round(p.val, 4))), 
                               HR, CI,
                               sep = "\n"),
                  pval.size = 4, pval.coord = c(0, 0.2),
                  conf.int = FALSE,
                  censor = TRUE,
                  palette = c("#DD492E","#40548A"),
                  font.legend = 16,
                  risk.table = TRUE,
                  legend = c(0.8, 0.9),
                  font.title = 14,
                  font.x = c(14, "bold.italic", "red"),
                  font.y = c(14, "bold.italic", "red")
  ) + labs(x = "Years",y=s) #Select units
  
  pdf(paste0("Fig1h_YchrS_level_Surv_",s,'.pdf'), width = 5, height = 6, onefile=F)
  print(p)
  dev.off()
  print(p)
}

```

```{r Fig 1g}
meta <- read_excel("Extended Data Table 1.xlsx")
data <- read_excel("Extended Data Table 3.xlsx")
data <- merge.data.frame(meta,data,by='Sample')
data$YchrS_level <- factor(data$YchrS_level,levels=c('WTY_BR','LOY_BR'))
```

```{r Fig 1g}
cancertypes <- unique(data$CancerType)
cor_res <- data.frame()
for(canc in cancertypes){
  sub_data <- data[data$CancerType==canc,c('YchrS','CTA Score')]
  sub_data <- na.omit(sub_data)
  if(nrow(sub_data)<5) next
  cor_t <- cor.test(sub_data$YchrS, sub_data$'CTA Score')
  cor_res[canc,'pval'] <- cor_t$p.value
  cor_res[canc,'corr'] <- cor_t$estimate[['cor']]
  cor_res[canc,'CI_L'] <- cor_t$conf.int[1]
  cor_res[canc,'CI_R'] <- cor_t$conf.int[2]
}
cor_res$Cancertype <- rownames(cor_res)
cancertypes <- cor_res$Cancertype[order(cor_res$corr)]
cor_res$Cancertype <-factor(cor_res$Cancertype ,levels=cancertypes)
```

```{r Fig 1i}
cor_res$logp <- -log10(cor_res$pval)
cor_res$sig<- ifelse(cor_res$pval<0.05,'*','ns')
p <- ggplot(cor_res,aes(x=Cancertype,y=corr,fill=corr))+
  geom_errorbar(aes(ymin=0,ymax=corr,width=0,color=sig),linewidth=1)+
  geom_point(aes(size=logp,fill=corr,color=sig),shape=21)+
  scale_color_manual(values=c('*'='#60646b','ns'='grey'))+
  scale_fill_gradientn(colours = c("#1fa4db","#f2f2f1","#f15b32"), values = rescale(c(min(cor_res$corr),0,max(cor_res$corr))), guide = "colorbar")+ 
  scale_y_continuous(expand = expansion(mult = 0))+coord_cartesian(ylim=c(-0.4,0.2))+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))
pdf('Fig1i_TCGA_CTA_YchrS_cor_R.pdf',6,3)
print(p)
dev.off()
```
